// Computes all-time AFL (men's) regular-season standings from linear_title.json.
// The linear_title.json events only record title changes, so we need the raw
// game data. We reuse the same Squiggle-sourced linear_title.json which we
// augment with full-season results via a second fetch from the same file.
//
// NOTE: linear_title.json only stores title-change *events*, not every game.
// For per-season standings we need a separate data source. This service falls
// back to fetching summary data from alltime_afl.json (generated by the build
// script), or returns null if that file doesn't exist.

let cache = null;

export async function loadAlltimeMens() {
  if (cache) return cache;
  const res = await fetch(`${import.meta.env.BASE_URL}alltime_afl.json`);
  if (!res.ok) {
    throw new Error(
      'All-time AFL data not found. Run `npm run build:alltime-afl` to generate it.'
    );
  }
  cache = await res.json();
  return cache;
}

export async function getSeasonStandings(year) {
  const data = await loadAlltimeMens();
  return data.seasons[year] ?? null;
}

export async function getAllSeasons() {
  const data = await loadAlltimeMens();
  return Object.keys(data.seasons).map(Number).sort((a, b) => b - a);
}

export async function getAlltimeTotals() {
  const data = await loadAlltimeMens();
  const totals = {};
  for (const [year, season] of Object.entries(data.seasons)) {
    for (const row of season.standings || []) {
      if (!totals[row.team]) {
        totals[row.team] = { wins: 0, losses: 0, draws: 0, played: 0, seasons: 0 };
      }
      totals[row.team].wins   += row.wins;
      totals[row.team].losses += row.losses;
      totals[row.team].draws  += row.draws;
      totals[row.team].played += row.played;
      totals[row.team].seasons += 1;
    }
  }
  return Object.entries(totals)
    .map(([team, s]) => ({
      team,
      ...s,
      winPct: s.played > 0 ? Math.round((s.wins + s.draws * 0.5) / s.played * 1000) / 10 : 0,
      pts: s.wins * 2 + s.draws,
    }))
    .sort((a, b) => b.winPct - a.winPct || b.wins - a.wins);
}

export async function getAlltimeGeneratedAt() {
  const data = await loadAlltimeMens();
  return data.generatedAt ?? null;
}

export async function getTrophyWinners() {
  const data = await loadAlltimeMens();
  // Returns array of { year, winner, wins, losses, draws, pct }
  return Object.entries(data.seasons)
    .map(([year, s]) => ({ year: Number(year), ...s.trophy }))
    .sort((a, b) => b.year - a.year);
}
